### ISSUE TITLE
No new line

### ISSUE THREAD

**Issue by petersell** [monferrand/mzettel#3] opened 2020-07-03 13:58 UTC
Unfortunately there is no new line anymore. Maybe it´so after a VSCode update? What is the syntax for a new line within the settings?

Cool programme, thank you very much.

**Comment by petersell** [comment] 2020-07-05 18:27
If I am editing the `package.json` the line break works. Therefore I leave the `settings.json` empty.

**Comment by nixsee** [comment] 2020-08-08 19:43
I have the same question - when I modify the file template, all of the parameters end up on the same line.

Here is an example - all I did was insert a space after "references" and now the line breaks are gone. 

![image](https://user-images.githubusercontent.com/24255237/89718614-213ce600-d97d-11ea-920f-ad13072fb5e2.png)

![image](https://user-images.githubusercontent.com/24255237/89718604-15e9ba80-d97d-11ea-861f-34a38a3141d8.png)

**Comment by monferrand** [comment] 2020-08-19 12:02
Hi,

Could I see your new template in settings.json?

A new line should be created for each element of the notesTemplate array:
```
"mzettel.notesTemplate":  [
            "*${date}*",   
            "> tags: ", 
            "",
            "> references: ",
            "---",
            "# ${title}",
            "",
            "",
            "",
            "---",
            "Links:",
            ">   - "
          ]
```

**Comment by Cages-hub** [comment] 2021-12-02 14:52
The issue might be the type is string in package.json
```
        "mzettel.notesTemplate": {
          "type": "string",
```

**Comment by monferrand** [comment] 2022-01-13 23:07
I'm not able to reproduce the issue, but you might be right about the type. I changed it in the new version. Is it better?

**Comment by Cages-hub** [comment] 2022-01-16 16:42
Yes the change fixes the issue and now each parameter of note template is now on a separate line

**Comment by monferrand** [comment] 2022-01-16 17:13
Perfect, I will close the issue then.

**Closed as completed by monferrand** 2022-01-16 17:13 UTC
