### ISSUE TITLE
Cannot Edit File Template without line breaks disappearing. 

### ISSUE THREAD

**Issue by nixsee** [monferrand/mzettel#5] opened 2020-08-08 19:44 UTC
When I modify the file template, all of the parameters end up on the same line.

Here is an example - all I did was insert a space after "references" and now the line breaks are gone and commas are shown as well.

![image](https://user-images.githubusercontent.com/24255237/89718614-213ce600-d97d-11ea-920f-ad13072fb5e2.png)

![image](https://user-images.githubusercontent.com/24255237/89718604-15e9ba80-d97d-11ea-861f-34a38a3141d8.png)

_Originally posted by @nixsee in https://github.com/monferrand/mzettel/issues/3#issuecomment-670966581_

**Comment by monferrand** [comment] 2022-01-13 23:13
Duplicate of https://github.com/monferrand/mzettle/issues/3

**Closed as completed by monferrand** 2022-01-13 23:13 UTC
